# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "ATLeS: Automated Tracking and Learning System"
shorttitle: ATLeS
email: atles@iwu.edu
description: > # this means to ignore newlines until next unindented line.
 An inexpensive, open-source system for automated, high-throughput, realtime observation and conditioning experiments.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: liffiton
repository: liffiton/ATLeS
show_downloads: false

header_pages:
  - "docs.md"

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - old/
  - dev/
